# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
gems:
  - jemoji
  - jekyll-sitemap

# Permalinks
permalink: /:year/:month/:day/:title

# Setup
title: CQUPTIOT
tagline: 'Hello everything'
#description: '<a href="https://twitter.com/ztpala" target="_blank">@ztpala</a>，关注<a href="/tag/#iOS">iOS</a>，<a href="/category/#空手道">空手道</a>，<a href="/category/#自行车">自行车</a>以及足球。'
description:
url: http://cquptiot.com
domain: cquptiot.com
twitterID: ztpala
timezone: America/New_York
subscribe: http://cquptiot.com/atom.xml
exclude: [ README.md, newpost.rb, CNAME ]
baseurl: "/"

author:
  name:           'Kaleo'
  url:            https://kaleocheng.com

paginate:         5

github:
  repo:           https://github.com/cquptiot/cquptiot.github.io.git
  githubEditBaseURL: https://github.com/pala/pala.github.com/edit/master/
